name: Publish

on:
  push:
    tags:
      - '**'

  # Enable button for manual trigger
  workflow_dispatch:

# Environment variables used as input
env:
  CODE: 'COVAC'
  # Name or Type (aggregate, tracker, event, add_on)?
  NAME: 'Registry'
  TYPE: 'tracker'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Prepare matrix'
        id: set-matrix
        run: echo "::set-output name=matrix::$(bash .github/scripts/prepare.sh)"


  publish:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Upload package'
        uses: prewk/s3-cp-action@master
#        with:
#           TODO: set ACL "--acl public-read" when public
#           Symlinks? --follow-symlinks
#           Delete? --delete
#          args:
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BOT_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BOT_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE: ${{ matrix.files.source }}
          DEST: "s3://${{ secrets.S3_BUCKET }}/${{ matrix.files.destination }}"
