name: Publish

on:
  push:
    branches:
      - test
#    tags:
#      - test-D2.35/1.1.3
#  pull_request:
#    branches:
#      - test
#    tags:
#      - test-D2.35/1.1.3

  # Enable button for manual trigger
  workflow_dispatch:

# Environment variables used as input
env:
  BUCKET: 'test-metadata.dhis2.org'
  CODE: 'COVAC'
  # Name or Type (aggregate, tracker, event, add_on)?
  NAME: 'Registry'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Set destination'
        #
        # GITHUB_REF - tag "D2.35/1.1.3", branch "2.35"
        #
        # Can be split:
        #
        # SPLIT_REF=(${GITHUB_REF//\// }) - split into array by "/"
        # DHIS=${SPLIT_REF[0]#D} - remove "D" from 1st part "D2.35"
        # META=${SPLIT_REF[1]} - 2nd part "1.1.3"
        #
        # Remove ref prefix and construct destination for upload
        run: |
          case $GITHUB_REF in
            refs/heads/*)
                SHORT_REF="${GITHUB_REF#refs/heads/}";;
            refs/tags/*)
                SHORT_REF="${GITHUB_REF#refs/tags/}";;
          esac
          echo "DESTINATION=$CODE/$NAME/$SHORT_REF/" >> $GITHUB_ENV

      - name: 'Upload to S3 Bucket'
        # TODO: Fix dockerfile, don't install aws-cli every time
        uses: dhis2/s3-sync-action@master
        with:
          # TODO: set ACL "--acl public-read" when public
          # Symlinks?
          # Delete?
          args: --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ env.BUCKET }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'complete/metadata.json'
          DEST_DIR: ${{ env.DESTINATION }}
          #
          # For a "tag" the DESTINATION will look like:
          #
          # test-metadata.dhis2.org/COVAC/Registry/D2.35/1.1.3/metadata.json
          # test-metadata.dhis2.org/COVAC/Registry/D2.35/1.1.2/metadata.json
          # test-metadata.dhis2.org/COVAC/Registry/D2.35/1.1.1/metadata.json
          # test-metadata.dhis2.org/COVAC/Registry/D2.34/1.1.3/metadata.json
          # test-metadata.dhis2.org/COVAC/Registry/D2.34/1.1.2/metadata.json
          # test-metadata.dhis2.org/COVAC/Registry/D2.34/1.1.1/metadata.json
          #
          # "dhis2/metadata" or "metadata/dhis2" in S3?
